export global SizeSettings {
    out property <length> control-icon-height: 16px;
    out property <length> control-icon-big-height: 32px;
    out property <length> control-height: 32px;
    out property <length> control-big-height: 48px;
}

export global SpaceSettings {
    out property <length> default-spacing: 4px;
    out property <length> default-padding: 8px;
}

export global Icons {
    out property <image> editor: @image-url("../icons/file-code.svg");
    out property <image> calendar: @image-url("../icons/avatar.svg");
    out property <image> json: @image-url("../icons/share.svg");
}
